### ISSUE TITLE
Обработка изображения с веб-камеры

### ISSUE THREAD

**Issue by serykhelena** [ZharkovKirill/RandPic_Generator#10]
Осуществить обработку изображения с веб-камеры, а именно:
1. Создать ползунки в отдельном окне
2. Перевести изображение из RGB  в HSV
3. Настроить параметры для выделения определённого цвета
4. Использовать фильтрацию: фильтр Гаусса + морфологические операторы (dilate + erode) 
5. Вывести на экран оригинальное изображение и конечное обработанное 

P.S. это последнее задание для практики

**Comment by ZharkovKirill** [comment]
Задание выполнено, приведены примеры работы программы
