### ISSUE TITLE
Перевести картинку из цветового пространства RGB в оттенки серого 

### ISSUE THREAD

**Issue by serykhelena** [ZharkovKirill/RandPic_Generator#2]
Для этого удобно использовать cv2.cvtColor. Вывести на экран оригинальное изображение и новое (чёрно-белое)

**Comment by ZharkovKirill** [comment]
1)ТЗ выполнено 
2)При самостоятельной  реализации функции перевода, получается серая картинка, но она не выводится на экран, что странно типы данных совпадают и матрицы картинок идентичны, и картинка полученная с помощью imwrite идентична полученной с помощью библиотечной функции.

**Comment by serykhelena** [comment]
У тебя получается не сохраняется gray_img2?

**Comment by serykhelena** [comment]
Я в коде просто не вижу, чтобы ты её выводил...И вроде для картинок не обязательно создавать окна, cv2.imshow(), сам сделает

**Comment by serykhelena** [comment]
Да, нет...вроде всё ок. Всё сохранилось. Может ты забыл ещё imshow ?

**Comment by ZharkovKirill** [comment]
Я не дописывал cv2.imshow(), для gray_img2, потому что она выводится как черный экран, но сохраняется как серая картинка.
